language: node_js
node_js:
  - node
install:
  - npm install
script:
  - npm test
after_success:
  - npm run coverage
jobs:
  include:
    - stage: release
      node_js: lts/*
      deploy:
        script:
          - npx semantic-release
